version: '3'

services:
  sx-exchange-web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sx-exchange-php-fpm
      - sx-exchange-mysql-database
      - sx-exchange-mongo-database
    networks:
      - sx-network
#      - sx_message_network

  sx-exchange-php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - sx-exchange-mysql-database
      - sx-exchange-mongo-database
    networks:
      - sx-network
#      - sx_message_network

  sx-exchange-mysql-database:
    image: mysql/mysql-server:latest
#    restart: always
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_store
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql-database/data:/var/lib/mysql:rw
    networks:
      - sx-network

  sx-exchange-mongo-database:
    image: mongo:latest
#    restart: always
    restart: unless-stopped
    ports:
    - "27017:27017"
    volumes:
      - ./docker/mongo-database/data:/data/db:rw
    networks:
      - sx-network

networks:
  sx-network:
#  sx_message_network:
#    external: true